//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
public partial class SoapTestData {
    
    private int soapTestNumberField;
    
    private bool soapTestNumberFieldSpecified;
    
    private string soapTestStringField;
    
    /// <remarks/>
    public int SoapTestNumber {
        get {
            return this.soapTestNumberField;
        }
        set {
            this.soapTestNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SoapTestNumberSpecified {
        get {
            return this.soapTestNumberFieldSpecified;
        }
        set {
            this.soapTestNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SoapTestString {
        get {
            return this.soapTestStringField;
        }
        set {
            this.soapTestStringField = value;
        }
    }
}
